# .golangci.pipeline.yaml
# В v2 поле version либо не нужно, либо должно быть строкой. Лучше убрать.

run:
  # concurrency: 8 # Лучше не задавать, авто-детект работает лучше
  timeout: 10m
  tests: true
  # skip-dirs и skip-files ЗДЕСЬ БОЛЬШЕ НЕТ (Removed in v2)

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - revive
    - unused
    # staticcheck в v2 объединил в себе gosimple и stylecheck, имей в виду
    - staticcheck

linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-use-default: false

  # ВОТ СЮДА переехали твои skip-dirs
  exclude-dirs:
    - bin
    - vendor
    - var
    - tmp
    - .cache

  # ВОТ СЮДА переехали твои skip-files
  exclude-rules:
    - path: \.pb\.go$
      linters:
        - all
    - path: \.pb\.gw\.go$
      linters:
        - all

    # Твои старые текстовые исключения
    - text: 'G104'
      linters:
        - gosec
    - text: 'exported func .* returns unexported type .*, which can be annoying to use'
      linters:
        - revive
    - text: 'should have a package comment'
      linters:
        - revive
    - text: "don't use an underscore in package name"
      linters:
        - revive
